# Generated by Django 3.0.4 on 2020-07-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Пост', max_length=200, verbose_name='Название')),
                ('text', models.TextField(max_length=20, verbose_name='Текст')),
                ('photo', models.ImageField(default='media/default.png', upload_to='', verbose_name='Картинки')),
            ],
        ),
    ]
