# Generated by Django 3.0.4 on 2020-07-27 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
    ]
