# Generated by Django 3.0.4 on 2020-08-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/default.png', upload_to='', verbose_name='Загрузить фото')),
                ('photo_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Относится к записи')),
            ],
        ),
        migrations.DeleteModel(
            name='Post_images',
        ),
    ]
