# Generated by Django 3.0.4 on 2020-08-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200808_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimages',
            name='test_field',
            field=models.CharField(default='Подпись картинки', max_length=2000, verbose_name='Подпись картинки'),
        ),
    ]
