# Generated by Django 3.0.4 on 2020-08-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200813_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Статьи блога', 'verbose_name_plural': 'Статьи блога'},
        ),
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name': 'Картинки к постам', 'verbose_name_plural': 'Картинки к постам'},
        ),
    ]
