# Generated by Django 3.0.4 on 2020-08-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200813_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='photo_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Относится к посту'),
        ),
    ]
